name: Deploy to App Engine

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Deploy to App Engine
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '290.0.1'
        service_account_key: ${{ secrets.SERVICE_ACCOUNT }}
        export_default_credentials: true
    - id: Beta Deploy
        run: gcloud app deploy --project=${{ secrets.PROJECT_NAME }} --quiet --no-promote
  ##    uses: GoogleCloudPlatform/github-actions/appengine-deploy@master
  ##    with:
  ##      project_id: ${{ secrets.PROJECT_ID}}
